version: '3.8'

services:
  # Сервис api-server
  api-server:
    build:
      context: ./api-server
    container_name: api-server
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - core-server

  # Сервис core-server
  core-server:
    build:
      context: ./core-server  # Путь к проекту core-service
    container_name: core-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/userdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8081:8081"
    networks:
      - app-network
    depends_on:
      - postgres

  # База данных PostgreSQL
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=userdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
    ports:
      - "5433:5432"

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
